const KEYCLOAK_TOKEN_URL = "http://localhost:8083/realms/power-outage/protocol/openid-connect/token";
const API_URL = "http://localhost:8000/api/v1/outage-reports";
let accessToken = "";
const connection = document.querySelector("#connection"), loginButton = document.querySelector("#loginButton"), submitButton = document.querySelector("#submitButton"), refreshButton = document.querySelector("#refreshButton"), reportForm = document.querySelector("#reportForm"), formMessage = document.querySelector("#formMessage"), reportRows = document.querySelector("#reportRows");
const statusText = {RECEIVED:"Đã tiếp nhận", NOTIFIED:"Đã thông báo", NOTIFICATION_FAILED:"Thông báo thất bại"};
function setConnection(text,state){connection.textContent=text;connection.className=`status ${state}`;}
async function login(){loginButton.disabled=true;setConnection("Đang kết nối","waiting");formMessage.textContent="";try{const body=new URLSearchParams({grant_type:"password",client_id:"power-outage-api",username:"operator01",password:"operator123"});const response=await fetch(KEYCLOAK_TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});if(!response.ok)throw new Error("Không thể đăng nhập Keycloak");accessToken=(await response.json()).access_token;setConnection("Hệ thống hoạt động","connected");submitButton.disabled=false;refreshButton.disabled=false;await loadReports()}catch(error){setConnection("Mất kết nối","error");formMessage.textContent=`${error.message}. Hãy kiểm tra Docker đang chạy.`}finally{loginButton.disabled=false}}
async function apiRequest(url,options={}){const response=await fetch(url,{...options,headers:{Authorization:`Bearer ${accessToken}`,...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||`Yêu cầu thất bại (${response.status})`);return payload}
async function loadReports(){reportRows.innerHTML='<tr><td colspan="5" class="empty">Đang tải dữ liệu...</td></tr>';try{const page=await apiRequest(`${API_URL}?page=0&size=20`),reports=page.content||[];reportRows.innerHTML=reports.length?reports.map(report=>`<tr><td><strong>${report.reportCode}</strong></td><td>${report.customerCode}</td><td>${report.servicePointCode}</td><td><span class="badge">${statusText[report.status]||report.status}</span></td><td>${new Date(report.createdAt).toLocaleString("vi-VN")}</td></tr>`).join(""):'<tr><td colspan="5" class="empty">Chưa có báo cáo nào.</td></tr>'}catch(error){reportRows.innerHTML=`<tr><td colspan="5" class="empty error-text">${error.message}</td></tr>`}}
reportForm.addEventListener("submit",async event=>{event.preventDefault();submitButton.disabled=true;formMessage.textContent="Đang gửi yêu cầu...";try{const report=await apiRequest(API_URL,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(Object.fromEntries(new FormData(reportForm).entries()))});formMessage.textContent=`Tiếp nhận thành công — Mã: ${report.reportCode}`;await loadReports();document.querySelector("#history").scrollIntoView({behavior:"smooth"})}catch(error){formMessage.textContent=error.message}finally{submitButton.disabled=false}});
loginButton.addEventListener("click",login);refreshButton.addEventListener("click",loadReports);login();
